// This is not used anymore, refer to the locale files

export enum SiteText {
    contact = "Tell us a little bit about your project, we will get back to you at the earliest",
    companyName = "Orus Solutions",
    description = "Description",
    headerTitleLeftPart = "We are ready to Get",
    headerGradientPart = "partner of choice",
    headerTitleRightPart = "for the startups",
    headerSubtitle = "We help businesses elevate their value through custom software development, product design, quality assurance and consultancy services.",
    discoveryButton = "Discover",
    ourServices = "Our Services",
    lorem = "lorem ipsum",
    longLorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    engagementOpener = "What you can expect from us",
    engagementTitle = "Engagement solutions",
    engagementSubtitle1 = "We help you solve simple or complex business problems with technology solutions.Together, with our diverse experts, we help clients overcome business challenges with custom software engineering and consultancy services that add tangible value.",
    engagementSubtitle2 = "We’re passionate about our cross-functional approach. We help you design, test, build and deliver products – faster and more cost-effectively. Orus Solutions cooperation models offer flexibility, so we can match our services to your goals, resources and timeline. We’re proud to contribute to the success of the world’s leading brands.",
    engagementCta = "Sounds good! Let's do it!",
    email = "Enter email...",
    subscribe = "Subscribe",
    serviceOpener = "What we can do for you",
    serviceTitle = "Services that lead the way to better business",
    valueOpener = "What we prone",
    valueTitle = "Our values",
    ctaTitle = "Contact us",
    teamTitle = "Meet our team",
    startTitle = "A workplace where talent, creativity and passion come together.",
    startDescription = "Here at Orus Solutions we take special care of what your organization needs. We review each and every client business and oversee the team that tailores a solution.",
    startButton = "Let's get started",
    footerDescription = "We help customer to build the best product that suits them.",
    contactEmail = "contact@orusllc.com",
    contactPhone = "+1 122 256 15",
    contactPlace = "US | Madagascar"
}